### ISSUE TITLE
Uncaught Error: Pagemark has no percentage

### ISSUE THREAD

**Issue by leogodin217** [burtonator/polar-bookshelf#1038]
**Describe the bug**
Getting error: "Uncaught Error: Pagemark has no percentage" whenever I open a specific PDF document. All functionality seems to work, so this is not a big deal. I tried deleting all the pagemarks I could find, but I still get the error. Maybe I created a zero-length pagemark?

**To Reproduce**
1. Double click the document in the document repository. 
2. Once the document opens I see a red message: "An internal error has occurred."
3. Developer tools > Console shows "listener generated unhandled exception:  Error: Pagemark has no percentage"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  1.19.8

**Additional context**
Full error:

[error] [1.19.8] [Reactor.js] listener generated unhandled exception:  Error: Pagemark has no percentage
    at ThumbnailPagemarkComponent.render (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\pagemarks\view\components\AbstractPagemarkComponent.js:63:19)
    at callback (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\components\ComponentManager.js:44:31)
    at ComponentManager.onComponentEvent (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\components\ComponentManager.js:54:17)
    at Object.onMutation (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\PageMetas.js:65:17)
    at C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\proxies\TraceListenerExecutor.js:26:35
    at Array.forEach (<anonymous>)
    at TraceListenerExecutor.sync (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\proxies\TraceListenerExecutor.js:14:29)
    at C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\PageMetas.js:67:16
    at C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\util\Functions.js:46:13
    at Array.forEach (<anonymous>)
    at Function.forDict (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\util\Functions.js:44:14)
    at Object.forDict (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\util\Functions.js:93:22)
    at Function.createModel (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\PageMetas.js:51:21)
    at PagemarkModel.registerListener (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\pagemarks\model\PagemarkModel.js:7:31)
    at ComponentManager.onDocumentLoaded (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\components\ComponentManager.js:27:22)
    at C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\reactor\Reactor.js:45:17
    at Array.forEach (<anonymous>)
    at Reactor.dispatchEvent (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\reactor\Reactor.js:43:30)
    at Model.<anonymous> (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\model\Model.js:56:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\leogo\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\model\Model.js:4:58)

**Comment by burtonator** [comment]
What version of polar?

**Comment by leogodin217** [comment]
Sorry about that. I wrote a fairly detailed bug report, but somehow saved the template. I updated with the full report.

**Comment by burtonator** [comment]
Could this be an older document by any chance?

**Comment by leogodin217** [comment]
It was added in March, but I only recently started working with it.  I found the issue. There was a pagemark with "percentage": 0 in the state.json. I deleted it and it is working fine now.

**Comment by burtonator** [comment]
Ah.. this is in fact a second bug too that was fixed. Will be resolved in the next release but seems like you have a workaround for now.
