### ISSUE TITLE
Setting a pagemark above the beginning of the document gives an error

### ISSUE THREAD

**Issue by aidanhs** [burtonator/polar-bookshelf#1267]
**Describe the bug**
Setting a pagemark above the first page of a document gives an error

**To Reproduce**
1. Go to "large scale cluster management at google with borg" (sample doc)
2. Scroll to the top
3. Right click in the black margin just above the first page
4. Press "create pagemark to point"
5. See error

From error.log:
```
[2019-12-19T22:00:11.264Z] [error] [error] [1.80.3] Failed to create pagemark: 
Error: Assertion failed for value -0.10395010395010396: height
    at Function.assert (/snap/polar-bookshelf/80/resources/app.asar/node_modules/polar-shared/src/Preconditions.js:14:19)
    at PagemarkRect._validate (/snap/polar-bookshelf/80/resources/app.asar/web/js/metadata/AnnotationRect.js:22:39)
    at new AnnotationRect (/snap/polar-bookshelf/80/resources/app.asar/web/js/metadata/AnnotationRect.js:14:14)
    at new PagemarkRect (/snap/polar-bookshelf/80/resources/app.asar/web/js/metadata/PagemarkRect.js:4:1)
    at Function.createFromRect (/snap/polar-bookshelf/80/resources/app.asar/web/js/metadata/PagemarkRects.js:29:16)
    at createPagemarkRect (/snap/polar-bookshelf/80/resources/app.asar/web/js/metadata/Pagemarks.js:53:54)
    at /snap/polar-bookshelf/80/resources/app.asar/web/js/metadata/Pagemarks.js:84:30
    at Function.withMutating (/snap/polar-bookshelf/80/resources/app.asar/web/js/metadata/DocMetas.js:127:20)
    at Function.withBatchedMutations (/snap/polar-bookshelf/80/resources/app.asar/web/js/metadata/DocMetas.js:116:21)
    at Function.updatePagemarksForRange (/snap/polar-bookshelf/80/resources/app.asar/web/js/metadata/Pagemarks.js:81:29)
```

**Expected behavior**
There should be no error (and the document pagemark should be reset to the document start)

**Screenshots**
Available on request.

**Desktop (please complete the following information):**
 - OS: Linux (snap)
 - Browser: N/A?
 - Version: Ubuntu 18.04

**Additional context**
 - A likely-similar error happens when clicking below the bottom of the document.
 - (I also saw this error once when just clicking around playing with pagemarks in the middle of a doc, but can't reproduce)

**Comment by burtonator** [comment]
n/a in 2.0
