### ISSUE TITLE
Uncaught Exception: HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by or-dodson** [burtonator/polar-bookshelf#1341]
**Describe the bug**
Program crashed with net::ERR_HTTP_RESPONSE_CODE_FAILURE

**To Reproduce**
Steps leading up to crash  
1. Put laptop in hibernation mode while connected to wifi with Polar open in background
2. Travel to an eduroam wifi network
3. Start laptop out of hibernation mode

**Expected behavior**
Polar catches error and handles it internally

**Screenshots**  
![image](https://user-images.githubusercontent.com/48970011/73077339-389f0080-3e7d-11ea-8cda-d6bf4b0c2f54.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: Polar 1.90.0

**Comment by or-dodson** [comment]
Error also appeared twice while opening a document, moving to a bookmark, and then zooming.

**Comment by hikerito** [comment]
Same error, Polar 1.90, MacOS 14
In my case it happens when I open a captured web page. Once it's open, it begins throwing little windows with those messages and OK button, one after the other, once I close one, another appears. I have to kill Polar. Apparently, no way to read a captured page now while the problem is there.

**Comment by hikerito** [comment]
Arh now it won't start at all, those windows appear when "Initializing firestore". Maybe its db got corrupted when I "force quit"  it the last time...

**Comment by hikerito** [comment]
Alright so an hour later it started without problem, and opened a captured page without problem. Could it be an error when checking for an update? It decided not to check any more today? Anyway at the moment I can't reproduce it. No errors at the moment.

**Comment by or-dodson** [comment]
It just became so bad for me (the screen pops back up after closing it), that I'm reverting to the previous version.

**Comment by rgoulter** [comment]
Snippet of the tail of ~/.polar/logs/error.txt

Seems to indicate the calls to sentry are failing, due to hitting the rate limit.

```
[2020-01-26T17:54:54.588Z] [error] [error] [1.90.0] Unhandled rejection: 
SentryError: HTTP Error (429): Creation of this event was denied due to rate limiting
    at new SentryError (C:\Users\USER\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\@sentry\core\dist\error.js:21:28)
    at ClientRequest.<anonymous> (C:\Users\USER\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\@sentry\electron\dist\main\transports\net.js:44:36)
    at ClientRequest.emit (events.js:203:13)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at URLRequest.<anonymous> (electron/js2c/browser_init.js:2402:12)
    at URLRequest.emit (events.js:203:13)
    at URLRequest.EventEmitter.emit (domain.js:476:20)
    at URLRequest.topLevelDomainCallback (domain.js:131:23)
[2020-01-26T17:54:54.592Z] [error] [error] [1.90.0] Uncaught exception: 
Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

So, don't bet on consistent reproduction steps.

I guess a temporary workaround for users would be to block sentry.io

**Comment by 92hertz** [comment]
I started using Polar Bookshelf for college reading two days ago and have already had this error twice. I didn't know where else to go with this issue so I'm seeing if you guys have any tips on a workaround. I am running Mac OS 10.14.6 and this error box keeps coming up, keeping me from using the app without force killing it. The first time it threw this error was when I created my first pagemark on a good sized Biochemistry textbook, and now this morning it gave me the error again as soon as I opened the book again.

Below is a screen shot of the error window which persists even when I click OK.

<img width="423" alt="Screen Shot 2020-01-28 at 9 00 39 AM" src="https://user-images.githubusercontent.com/60393213/73270473-baa86580-41ac-11ea-81a0-a6339558d79b.png">

Let me know if there is any other information that would be helpful. I like Polar but I will stop using it if I can't resolve this problem.

**Comment by Ooglogput** [comment]
I get this same error a lot when I try to resize a pagemark box. On Linux.

**Comment by rgoulter** [comment]
@92hertz I think running Polar Bookshelf while offline would avoid this error until it's otherwise fixed. (Then just turn internet on to re-sync once you're done, if you use multiple devices).

If that's inconvenient, see if blocking the domain "sentry.io" works. e.g. following steps like
https://www.techjunkie.com/edit-hosts-file-mac-os-x/

**Comment by burtonator** [comment]
Thanks for reporting this guys. I think this is fixed in the next release which I"m trying to get out the door.
