### ISSUE TITLE
Latest release crashes on Windows 10

### ISSUE THREAD

**Issue by GeorgeHahn** [burtonator/polar-bookshelf#1344]
**Describe the bug**
When I start Polar Bookshelf, the application window flashes for a brief moment before disappearing.

**To Reproduce**
1. Launch Polar Bookshelf (directly or from a shortcut)
2. Window appears briefly (50ms?) and disappears. No Polar Bookshelf processes remain afterwards.

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1909
  - This is a fairly new install and probably doesn't have 
 - Browser: Firefox
 - Version 72

**Additional context**

Command line output:

```
Allowing pre-releases for auto-updates: false
Auto updates enabled.
Scheduling auto update for N ms: 215836248.31536868
Running with CWD: C:\Users\george\AppData\Local\Programs\polar-bookshelf
Running with Node version: v12.8.1
Running with Electron version: 7.1.2
Running with Polar version: 1.90.15
Running with app version: 1.90.15
Mon, 03 Feb 2020 05:33:06 GMT body-parser deprecated undefined extended: provide extended option at resources\app.asar\node_modules\polar-shared-webserver\src\webserver\Webserver.js:90:35
[notice] [1.90.15] External navigation block enabled: true
```

**Comment by 820239854** [comment]
Yes,I'm facing the same problem.

**Comment by FluffyBucket** [comment]
I have the same problem. It worked fine for a while, but then it suddenly crashed and now I experience the same thing as @GeorgeHahn.
I looked around in the crash folder (`<UserName>/AppData/Local/Temp/polar-bookshelf Crashes`)
And the `operation_log.txt` only contains this line multiple times `ERROR:crash_report_database_win.cc(469)] failed to stat report`

**Comment by or-dodson** [comment]
I had the same problem. A fresh install after an uninstall seems to fix the problem as far as I can tell.

**Comment by burtonator** [comment]
Super frustrating and sorry that hit you guys. 

If I cut a new release could you guys provide feedback ?  I *think* it's an issue with sentry (which we use for reporting errors) but I'm not sure.  It that's the issue I'm going to ditch it as it's causing more trouble than it's worth.

**Comment by burtonator** [comment]
Here's a quick idea.

If you can start Polar from the command line you should be able to set ```POLAR_SENTRY_ENABLED=false```  and that *should* run without sentry.  That's really the only major thing that's changed in that release.  

Does the entire Electron exit ? does it 'crash' or does the window just vanish?

**Comment by or-dodson** [comment]
So running it from powershell does reproduce the crash. Interesting enough, running the same executable from a linux based BASH (I use MSYS) does not produce the crash.  
I tried running it with the sentry disabled -- either I wasn't able to properly set it or sentry isn't the problem because it still crashed with essentially the same message.

Here's the output from running it from powershell with no flags:

` Allowing pre-releases for auto-updates: false
Auto updates enabled.
Scheduling auto update for N ms: 125204699.16214122
Running with CWD: C:\users\ordod\AppData\Local\Programs\polar-bookshelf
Running with Node version: v12.8.1
Running with Electron version: 7.1.2
Running with Polar version: 1.90.15
Running with app version: 1.90.15
Loaded prefs from: C:\Users\ordod\.polar\config\prefs.json
Thu, 06 Feb 2020 20:42:31 GMT body-parser deprecated undefined extended: provide extended option at resources\app.asar\node_modules\polar-shared-webserver\src\webserver\Webserver.js:90:35
[30564:26580:0206/134237.233:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.234:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.240:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.241:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.244:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.245:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.246:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.246:ERROR:crash_report_database_win.cc(469)] failed to stat report
[notice] [1.90.15] External navigation block enabled: true
[30564:26580:0206/134237.247:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.249:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.250:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.252:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.253:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.254:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.255:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.257:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.258:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.261:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.264:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.269:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.272:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.277:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.281:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.283:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.285:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.286:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.287:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.288:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.290:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.293:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.294:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.296:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.297:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.298:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.299:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.300:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.301:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.304:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.531:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.535:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.538:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.541:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.542:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.543:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.547:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.551:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.553:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.555:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.556:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.557:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.560:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.568:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.571:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.573:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.575:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.580:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.584:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.585:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.591:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.596:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.602:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.605:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.609:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.610:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.615:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.620:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.625:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.628:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.634:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.637:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.639:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.641:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.644:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.656:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.659:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:1396:0206/134237.671:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.679:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.682:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.731:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.744:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.747:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.748:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.749:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.750:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.751:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.752:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.764:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.765:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.766:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.767:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.768:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.769:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.770:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.771:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.772:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.772:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.773:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.774:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.781:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.783:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.784:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.785:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.786:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.787:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.788:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.789:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.790:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.796:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.808:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.812:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.824:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.829:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.830:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.830:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.835:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.848:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.852:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.865:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.868:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.878:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.880:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.889:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.895:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.900:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.905:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.911:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.916:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.918:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.919:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.920:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.921:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.924:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.926:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.927:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.928:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.930:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.934:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.936:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.938:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.939:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.939:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.940:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.941:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.941:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.942:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.943:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.944:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.944:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.945:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.945:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.946:ERROR:crash_report_database_win.cc(469)] failed to stat report
[30564:26580:0206/134237.947:ERROR:crash_report_database_win.cc(469)] failed to stat report`

**Comment by burtonator** [comment]
If you can reproduce it you're definitely going to be my hero.

I'm working on a new build which completely disables sentry.  I realized that this var, while it isn't "using" sentry, still imports it and it might have side effects on the import.

I'll have a pre-release build out tonight/tomorrow.

**Comment by burtonator** [comment]
Can you guys try this build:

https://github.com/burtonator/polar-bookshelf/releases/tag/v1.90.17

**Comment by or-dodson** [comment]
This build seems to work on my system. Tried all the same steps that I got the last build to crash on and it always booted right up 👍.

**Comment by burtonator** [comment]
NICE! Well the good news is I found the bug.  The bad news is I have to ditch sentry... :-/

**Comment by burtonator** [comment]
@or-dodson Thanks a lot here!!  This really helps!!!

**Comment by FluffyBucket** [comment]
@burtonator The build also seems to work on my system. No crash yet.
