### ISSUE TITLE
Anki sync error

### ISSUE THREAD

**Issue by jjthomas41** [burtonator/polar-bookshelf#1360]
**Describe the bug**
Attempting to sync cards (tools >sync flashcards to anki) leads to error message: "An internal error has occurred: Missing the following required Anki models (the names may be in another language. Copy them to English card names for now): Cloze"

Polar connect add on is installed in anki version 2.1

**To Reproduce**
1. Go to 'Tools'
2. Click on 'sync flashcards to anki'
3. See error

**Expected behavior**
Cards to sync to anki. Notification of progress to appear in bottom of Polar Bookshelf window.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 1903
 - Browser Chrome
 - Version 1.90.18
- Anki Version 2.1.20 (47a1bf8b)
- Python 3.8.0 Qt 5.14.1

**Additional context**
The log shows:
Failed to start sync:  Error: Missing the following required Anki models (the names may be in another language.  Copy them to English card names for now): Cloze
    at Function.verifyRequired (C:\Users\Justin\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\apps\sync\framework\anki\ModelNames.js:12:19)
    at AnkiSyncEngine.<anonymous> (C:\Users\Justin\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\apps\sync\framework\anki\AnkiSyncEngine.js:44:37)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Justin\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\apps\sync\framework\anki\AnkiSyncEngine.js:5:58)

**Comment by NaturesTrail** [comment]
I have a similar error Windows 10 Pro 1909, OS 18363.657.  In my case,I get an error message 28  cards to sync and 8 errors.  However, there were only a total of 8 test cards.

For some reason three (3) of the cards synced, but the rest did not. Polar indicates no cards were synced.

**Comment by jason96** [comment]
me too, whether polar only support english card and deck?

**Comment by jjthomas41** [comment]
Thank you @jason96! That worked.

**Comment by jahentao** [comment]
> Thank you @jason96! That worked.

I have the same problem. What have you done? I don't understand. Can you help me?
