### ISSUE TITLE
New Error in Polar/Anki

### ISSUE THREAD

**Issue by hedonia** [burtonator/polar-bookshelf#1418]
Version 1.100.13 of Polar
Following error pops up on Anki whenever I try to sync new flashcards. Was working earlier today, stopped working after updating Anki Connect, so possibly has something to do with that?

After error in Anki, status bar stuck at "performing sync on x notes"; never finishes sync.

Debug info:
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-05 22:09:05
Add-ons possibly involved: ⁨Polar Connect - PDF and Incremental Reading with Anki Sync⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/mikewilson/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 309, in advance
    self.server.advance()
  File "/Users/mikewilson/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 217, in advance
    self.advanceClients()
  File "/Users/mikewilson/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 232, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/mikewilson/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 232, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/mikewilson/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 139, in advance
    self.writeBuff += self.handler(req)
  File "/Users/mikewilson/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 251, in handlerWrapper
    body = makeBytes(json.dumps(self.handler(params)))
  File "json/__init__.py", line 231, in dumps
  File "json/encoder.py", line 199, in encode
  File "json/encoder.py", line 257, in iterencode
  File "json/encoder.py", line 179, in default
TypeError: Object of type RepeatedScalarContainer is not JSON serializable

**Comment by iamef** [comment]
I am also getting this error.

**Comment by roboticsdude60** [comment]
Looks like there is a pull request to fix this in the polar-connect addon for anki
[](https://github.com/burtonator/polar-connect-anki/pull/2)
