### ISSUE TITLE
The addons of Polar connect doesn`t sync my flash cards to Anki

### ISSUE THREAD

**Issue by UNM4SK3D** [burtonator/polar-bookshelf#1442]
Dear Polar Community,

I can't sync my polar flashcards to anki and if I try to do it. 
This will always appear: 
Debug info:
Anki 2.1.28 (7d8818f8) Python 3.8.0 Qt 5.15.0 PyQt 5.15.0
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-02 17:00:27
Add-ons possibly involved: ⁨Polar Connect - PDF and Incremental Reading with Anki Sync⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/plantlexus/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 309, in advance
    self.server.advance()
  File "/Users/plantlexus/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 217, in advance
    self.advanceClients()
  File "/Users/plantlexus/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 232, in advanceClients
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/plantlexus/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 232, in <lambda>
    self.clients = list(filter(lambda c: c.advance(), self.clients))
  File "/Users/plantlexus/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 139, in advance
    self.writeBuff += self.handler(req)
  File "/Users/plantlexus/Library/Application Support/Anki2/addons21/734898866/__init__.py", line 251, in handlerWrapper
    body = makeBytes(json.dumps(self.handler(params)))
  File "json/__init__.py", line 231, in dumps
  File "json/encoder.py", line 199, in encode
  File "json/encoder.py", line 257, in iterencode
  File "json/encoder.py", line 179, in default
TypeError: Object of type RepeatedScalarContainer is not JSON serializable

Can you please help me with this? I thank you in advance.

Sincerely,

Plantlexus

**Comment by burtonator** [comment]
Fixed in 2.0
