### ISSUE TITLE
Installation from sources failed on Windows 10

### ISSUE THREAD

**Issue by CaptainRock** [burtonator/polar-bookshelf#1443]
[2020-08-05T11_56_58_200Z-debug.log](https://github.com/burtonator/polar-bookshelf/files/5028154/2020-08-05T11_56_58_200Z-debug.log)
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**Describe the bug**

**To Reproduce**
1. Go to '...' Source Dir
2. Run npm install && npm run-script compile && npm start
3. See error

**Expected behavior**
Polar should be installed
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Home Single Language
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dranion** [comment]
Looks like the specific problem is "**No matching version found for file-selector@0.1.13**", at multiple points throughout the log. First at '261 silly fetchPackageMetaData error for file-selector@=0.1.13 No matching version found for file-selector@0.1.13.' but it only fails here: 
```
5878 verbose stack file-selector: No matching version found for file-selector@0.1.13.
5878 verbose stack     at pickManifest (D:\Arup\Work\node_modules\npm\node_modules\npm-pick-manifest\index.js:122:13)
5878 verbose stack     at D:\Arup\Work\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:24:14
5878 verbose stack     at tryCatcher (D:\Arup\Work\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
5878 verbose stack     at Promise._settlePromiseFromHandler (D:\Arup\Work\node_modules\npm\node_modules\bluebird\js\release\promise.js:517:31)
5878 verbose stack     at Promise._settlePromise (D:\Arup\Work\node_modules\npm\node_modules\bluebird\js\release\promise.js:574:18)
5878 verbose stack     at Promise._settlePromiseCtx (D:\Arup\Work\node_modules\npm\node_modules\bluebird\js\release\promise.js:611:10)
5878 verbose stack     at _drainQueueStep (D:\Arup\Work\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
5878 verbose stack     at _drainQueue (D:\Arup\Work\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
5878 verbose stack     at Async._drainQueues (D:\Arup\Work\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
5878 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (D:\Arup\Work\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
5878 verbose stack     at processImmediate (internal/timers.js:456:21)
5879 verbose cwd D:\Arup\Projects\polar-bookshelf
5880 verbose Windows_NT 10.0.18362
5881 verbose argv "D:\\Arup\\Work\\node.exe" "D:\\Arup\\Work\\node_modules\\npm\\bin\\npm-cli.js" "install"
5882 verbose node v12.18.3
5883 verbose npm  v6.14.6
5884 error code ETARGET
5885 error notarget No matching version found for file-selector@0.1.13.
5886 error notarget In most cases you or one of your dependencies are requesting
5886 error notarget a package version that doesn't exist.
5886 error notarget
5886 error notarget It was specified as a dependency of 'polar-bookshelf'
```
In case it makes troubleshooting either. I don't build this myself.

**Comment by burtonator** [comment]
I'll up date the docs but the build is broken for now for 3rd parties.  We're using an NPM repo that requires us to create accounts and had them out.  We need to find an NPM repo that supports public access to our packages to fix this

**Comment by CaptainRock** [comment]
Thanks a lot for letting us know this 👍
