### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by LSWleecc** [burtonator/polar-bookshelf#1541]
when i execute npm run-script compile

apps/dev-dom-search/index.tsx:2:27 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

2 import * as ReactDOM from "react-dom";
                            ~~~~~~~~~~~

apps/dev2/index.tsx:2:27 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

2 import * as ReactDOM from "react-dom";
                            ~~~~~~~~~~~

apps/doc/src/annotations/AreaHighlightRenderer.tsx:8:27 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

8 import * as ReactDOM from "react-dom";
                            ~~~~~~~~~~~

apps/doc/src/annotations/PagemarkRendererForFixed.tsx:5:27 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

5 import * as ReactDOM from "react-dom";
                            ~~~~~~~~~~~

apps/doc/src/annotations/PagemarkRendererForFluid.tsx:3:27 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

3 import * as ReactDOM from "react-dom";
                            ~~~~~~~~~~~

apps/doc/src/annotations/TextHighlightRendererDynamic.tsx:2:27 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

2 import * as ReactDOM from "react-dom";
                            ~~~~~~~~~~~

apps/doc/src/annotations/TextHighlightRendererStatic.tsx:1:27 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

1 import * as ReactDOM from "react-dom";
                            ~~~~~~~~~~~

apps/doc/src/renderers/epub/contextmenu/EPUBIFrameMenuPortal.tsx:3:22 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

3 import ReactDOM from "react-dom";
                       ~~~~~~~~~~~

apps/doc/src/renderers/epub/EPUBFindRenderer.tsx:2:22 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

2 import ReactDOM from 'react-dom';
                       ~~~~~~~~~~~

apps/doc/src/renderers/pdf/PDFDocument.tsx:8:8 - error TS7016: Could not find a declaration file for module 'pdfjs-dist/web/pdf_viewer'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/pdfjs-dist/web/pdf_viewer.js' implicitly has an 'any' type.
  Try `npm install @types/pdfjs-dist` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdfjs-dist/web/pdf_viewer';`

8 } from 'pdfjs-dist/web/pdf_viewer';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~

apps/doc/src/renderers/pdf/PDFDocument.tsx:9:62 - error TS7016: Could not find a declaration file for module 'pdfjs-dist'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/pdfjs-dist/build/pdf.js' implicitly has an 'any' type.
  Try `npm install @types/pdfjs-dist` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdfjs-dist';`

9 import {LinkTarget, PDFDocumentProxy, PDFViewerOptions} from "pdfjs-dist";
                                                               ~~~~~~~~~~~~

apps/doc/src/renderers/pdf/PDFDocument.tsx:49:18 - error TS2503: Cannot find namespace '_pdfjs'.

49 import Outline = _pdfjs.Outline;
                    ~~~~~~

apps/doc/src/renderers/pdf/PDFDocument.tsx:52:22 - error TS2503: Cannot find namespace '_pdfjs'.

52 import Destination = _pdfjs.Destination;
                        ~~~~~~

apps/doc/src/renderers/pdf/PDFDocument.tsx:174:35 - error TS7006: Parameter 'progress' implicitly has an 'any' type.

174         loadingTask.onProgress = (progress) => {
                                      ~~~~~~~~

apps/doc/src/renderers/pdf/PDFDocument.tsx:258:56 - error TS2503: Cannot find namespace '_pdfjs'.

258         function createPageNavigator(pdfDocumentProxy: _pdfjs.PDFDocumentProxy): PageNavigator {
                                                           ~~~~~~

apps/doc/src/renderers/pdf/PDFFindControllers.ts:1:43 - error TS7016: Could not find a declaration file for module 'pdfjs-dist/web/pdf_viewer'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/pdfjs-dist/web/pdf_viewer.js' implicitly has an 'any' type.
  Try `npm install @types/pdfjs-dist` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdfjs-dist/web/pdf_viewer';`

1 import {EventBus, PDFFindController} from 'pdfjs-dist/web/pdf_viewer';
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~

apps/preview/index.ts:1:63 - error TS7016: Could not find a declaration file for module 'pdfjs-dist'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/pdfjs-dist/build/pdf.js' implicitly has an 'any' type.
  Try `npm install @types/pdfjs-dist` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdfjs-dist';`

1 import PDFJS, {DocumentInitParameters, PDFDocumentProxy} from 'pdfjs-dist';
                                                                ~~~~~~~~~~~~

apps/preview/index.ts:10:8 - error TS7016: Could not find a declaration file for module 'pdfjs-dist/web/pdf_viewer'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/pdfjs-dist/web/pdf_viewer.js' implicitly has an 'any' type.
  Try `npm install @types/pdfjs-dist` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdfjs-dist/web/pdf_viewer';`

10 } from 'pdfjs-dist/web/pdf_viewer';
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@material-ui/styles/withStyles/withStyles.d.ts:10:24 - error TS2694: Namespace '"/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/csstype/index"' has no exported member 'FontFace'.

10 type JSSFontface = CSS.FontFace & { fallbacks?: CSS.FontFace[] };
                          ~~~~~~~~

node_modules/@material-ui/styles/withStyles/withStyles.d.ts:10:53 - error TS2694: Namespace '"/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/csstype/index"' has no exported member 'FontFace'.

10 type JSSFontface = CSS.FontFace & { fallbacks?: CSS.FontFace[] };
                                                       ~~~~~~~~

node_modules/@sentry/electron/dist/dispatch.d.ts:9:22 - error TS2420: Class 'ElectronClient' incorrectly implements interface 'CommonClient'.
  Property 'setupIntegrations' is missing in type 'ElectronClient' but required in type 'CommonClient'.

9 export declare class ElectronClient implements CommonClient {
                       ~~~~~~~~~~~~~~

  node_modules/@sentry/types/dist/client.d.ts:66:5
    66     setupIntegrations(): void;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~
    'setupIntegrations' is declared here.

node_modules/polar-browsers/src/Browsers.ts:1:24 - error TS7016: Could not find a declaration file for module 'ua-parser-js'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/ua-parser-js/src/ua-parser.js' implicitly has an 'any' type.
  Try `npm install @types/ua-parser-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'ua-parser-js';`

1 import {UAParser} from "ua-parser-js";
                         ~~~~~~~~~~~~~~

node_modules/polar-browsers/src/Browsers.ts:34:37 - error TS2503: Cannot find namespace 'IUAParser'.

34 export interface RawBrowser extends IUAParser.IResult {
                                       ~~~~~~~~~

node_modules/polar-file-saver/src/FileSavers.ts:1:22 - error TS2307: Cannot find module 'file-saver' or its corresponding type declarations.

1 import {saveAs} from 'file-saver';
                       ~~~~~~~~~~~~

node_modules/polar-html/src/sanitize/HTMLSanitizer.ts:1:26 - error TS2307: Cannot find module 'sanitize-html' or its corresponding type declarations.

1 import sanitizeHtml from 'sanitize-html';
                           ~~~~~~~~~~~~~~~

node_modules/polar-pdf/src/pdf/PDFDocs.ts:4:8 - error TS7016: Could not find a declaration file for module 'pdfjs-dist'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/pdfjs-dist/build/pdf.js' implicitly has an 'any' type.
  Try `npm install @types/pdfjs-dist` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdfjs-dist';`

4 } from "pdfjs-dist";
         ~~~~~~~~~~~~

node_modules/polar-pdf/src/pdf/PDFThumbnailer.ts:2:53 - error TS7016: Could not find a declaration file for module 'pdfjs-dist'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/pdfjs-dist/build/pdf.js' implicitly has an 'any' type.
  Try `npm install @types/pdfjs-dist` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdfjs-dist';`

2 import {PageViewport, PDFPageProxy, Transform} from "pdfjs-dist";
                                                      ~~~~~~~~~~~~

node_modules/polar-pdf/src/pdf/PDFThumbnailer.ts:11:8 - error TS7016: Could not find a declaration file for module 'pdfjs-dist/web/pdf_viewer'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/pdfjs-dist/web/pdf_viewer.js' implicitly has an 'any' type.
  Try `npm install @types/pdfjs-dist` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdfjs-dist/web/pdf_viewer';`

11 } from "pdfjs-dist/web/pdf_viewer";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/polar-pdf/src/pdf/PDFWorkers.ts:1:19 - error TS7016: Could not find a declaration file for module 'pdfjs-dist'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/pdfjs-dist/build/pdf.js' implicitly has an 'any' type.
  Try `npm install @types/pdfjs-dist` if it exists or add a new declaration (.d.ts) file containing `declare module 'pdfjs-dist';`

1 import PDFJS from "pdfjs-dist";
                    ~~~~~~~~~~~~

node_modules/polar-shared-webserver/src/webserver/Webserver.ts:6:81 - error TS2307: Cannot find module 'express' or its corresponding type declarations.

6 import express, {Express, NextFunction, Request, RequestHandler, Response} from 'express';
                                                                                  ~~~~~~~~~

node_modules/polar-shared-webserver/src/webserver/Webserver.ts:7:25 - error TS2307: Cannot find module 'serve-static' or its corresponding type declarations.

7 import serveStatic from 'serve-static';
                          ~~~~~~~~~~~~~~

node_modules/polar-shared-webserver/src/webserver/Webserver.ts:14:26 - error TS2307: Cannot find module 'express-serve-static-core' or its corresponding type declarations.

14 import {PathParams} from 'express-serve-static-core';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/polar-shared-webserver/src/webserver/Webserver.ts:110:18 - error TS7006: Parameter 'req' implicitly has an 'any' type.

110         app.use((req, res, next) => {
                     ~~~

node_modules/polar-shared-webserver/src/webserver/Webserver.ts:110:23 - error TS7006: Parameter 'res' implicitly has an 'any' type.

110         app.use((req, res, next) => {
                          ~~~

node_modules/polar-shared-webserver/src/webserver/Webserver.ts:110:28 - error TS7006: Parameter 'next' implicitly has an 'any' type.

110         app.use((req, res, next) => {
                               ~~~~

node_modules/polar-shared-webserver/src/webserver/Webserver.ts:259:26 - error TS7006: Parameter 'req' implicitly has an 'any' type.

259         app.use(function(req, res, next) {
                             ~~~

node_modules/polar-shared-webserver/src/webserver/Webserver.ts:259:31 - error TS7006: Parameter 'res' implicitly has an 'any' type.

259         app.use(function(req, res, next) {
                                  ~~~

node_modules/polar-shared-webserver/src/webserver/Webserver.ts:259:36 - error TS7006: Parameter 'next' implicitly has an 'any' type.

259         app.use(function(req, res, next) {
                                       ~~~~

node_modules/polar-shared/src/tags/Tags.ts:1:25 - error TS2307: Cannot find module 'twitter-text' or its corresponding type declarations.

1 import twitter_txt from 'twitter-text';
                          ~~~~~~~~~~~~~~

node_modules/polar-shared/src/util/Fetch.ts:1:43 - error TS7016: Could not find a declaration file for module 'node-fetch'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/node-fetch/index.js' implicitly has an 'any' type.
  Try `npm install @types/node-fetch` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-fetch';`

1 import {Request, Response, BodyInit} from 'node-fetch';
                                            ~~~~~~~~~~~~

node_modules/polar-shared/src/util/Fetch.ts:3:37 - error TS7016: Could not find a declaration file for module 'node-fetch'. '/Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/node-fetch/index.js' implicitly has an 'any' type.
  Try `npm install @types/node-fetch` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-fetch';`

3 import {default as node_fetch} from 'node-fetch';
                                      ~~~~~~~~~~~~

node_modules/polar-shared/src/util/Slugs.ts:1:28 - error TS2307: Cannot find module 'stopword' or its corresponding type declarations.

1 import * as stopwords from 'stopword';
                             ~~~~~~~~~~

web/js/accounts/AccountActions.ts:8:26 - error TS2307: Cannot find module '../../../../polar-app-private/polar-hooks/functions/impl/stripe/StripeUtils' or its corresponding type declarations.

8 import {StripeMode} from "../../../../polar-app-private/polar-hooks/functions/impl/stripe/StripeUtils";
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

web/js/apps/card_creator/elements/schemaform/ReactSummernote4.tsx:6:22 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

6 import ReactDOM from 'react-dom';
                       ~~~~~~~~~~~

web/js/apps/repository/AppInitializer.tsx:20:27 - error TS2307: Cannot find module 'react-dom' or its corresponding type declarations.

20 import * as ReactDOM from "react-dom" ......

and when i execute npm start

App threw an error during load
Error: Cannot find module 'polar-shared/src/logger/Logger'
Require stack:
- /Users/lishiwei/Downloads/polar-bookshelf-master/web/js/electron/main.js
- /Users/lishiwei/Downloads/polar-bookshelf-master/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/lishiwei/Downloads/polar-bookshelf-master/web/js/electron/main.js:16:18)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)

can you help me thanks!

**Comment by burtonator** [comment]
Could you try: 

http://github.com/burtonator/polar-app

and look at DEV.md ?

I have to update the build instructions but if this works for you I can update those.  Polar is now a multi-repo app
