### ISSUE TITLE
Does not working behind a proxy

### ISSUE THREAD

**Issue by albertotn** [burtonator/polar-bookshelf#187]
The program is not working behind a proxy and with any url simply does not display anything, could you please add a proxy settings so I can test it again?

Thanks!

**Comment by burtonator** [comment]
Fascinating.. I think you need to configure OS level proxying just like you do with chrome... do you have that setup?

**Comment by burtonator** [comment]
This is good feedback though

**Comment by roachsinai** [comment]
I use shadowsocks on windows and set a global proxy, but when I signup for sync got an error:

![image](https://user-images.githubusercontent.com/9500049/50746625-eb002780-126a-11e9-96ec-a7538e028ff8.png)

And I think it will be great if add an proxy option like Dropbox.

**Comment by burtonator** [comment]
Could you try these command line switches?

https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

--proxy-server=address:port
Use a specified proxy server, which overrides the system setting. This switch only affects requests with HTTP protocol, including HTTPS and WebSocket requests. It is also noteworthy that not all proxy servers support HTTPS and WebSocket requests. The proxy URL does not support username and password authentication per Chromium issue.

--proxy-bypass-list=hosts
Instructs Electron to bypass the proxy server for the given semi-colon-separated list of hosts. This flag has an effect only if used in tandem with --proxy-server.

For example:

const { app } = require('electron')
app.commandLine.appendSwitch('proxy-bypass-list', '<local>;*.google.com;*foo.com;1.2.3.4:5678')
Will use the proxy server for all hosts except for local addresses (localhost, 127.0.0.1 etc.), google.com subdomains, hosts that contain the suffix foo.com and anything at 1.2.3.4:5678.

--proxy-pac-url=url
Uses the PAC script at the specified url.

--no-proxy-server
Don't use a proxy server and always make direct connections. Overrides any other proxy server flags that are passed.

**Comment by burtonator** [comment]
.. let me know if they work...

**Comment by roachsinai** [comment]
you mean I run exe in command line and append these setting like --proxy-server=... ?

**Comment by burtonator** [comment]
Yeah.

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/50748476-92ce2300-1274-11e9-8db2-2776894f6119.png)

Thanks for reply, but it seems the 500 error will not disappear itself. I mean each time open polar I got this. Even after I capture a new webpage or import a now pdf, polar only show this.

**Comment by roachsinai** [comment]
Should I reinstall polar?

**Comment by roachsinai** [comment]
On Manjaro KDE, `polar-bookshelf --proxy-server=127.0.0.1:1080` didn't the software.

![screenshot_20190107_135637](https://user-images.githubusercontent.com/9500049/50751322-4559b200-1284-11e9-8813-685bf4de513d.png)

**Comment by zicklag** [comment]
I'm behind an HTTP proxy with authentication and I have my proxy settings set through environment variables and through dconf on Ubuntu 16.04. Running on the commandline yields:

```
> polar --proxy-server=127.0.0.1:3128
3523 3503
[Updates.js] Allowing pre-releases for auto-updates: false
[Updates.js] Auto updates disabled.
Running with app path: /tmp/.mount_polarANrwu0/resources/app.asar
Running with CWD: /home/username/bin
Running with node version: v12.0.0
body-parser deprecated undefined extended: provide extended option ../../../tmp/.mount_polarANrwu0/resources/app.asar/web/js/backend/webserver/Webserver.js:55:44
[error] [1.19.4] [Capture.js] Loading URL failed:  { Error: ERR_TUNNEL_CONNECTION_FAILED (-111) loading 'https://pingcap.com/blog/2017-07-11-tidbinternal1'
    at rejectAndCleanup (/tmp/.mount_polarANrwu0/resources/electron.asar/browser/navigation-controller.js:72:21)
    at WebContents.failListener (/tmp/.mount_polarANrwu0/resources/electron.asar/browser/navigation-controller.js:82:11)
    at WebContents.emit (events.js:199:15)
  errno: -111,
  code: 'ERR_TUNNEL_CONNECTION_FAILED',
  url: 'https://pingcap.com/blog/2017-07-11-tidbinternal1' }
```

**Comment by FrisaSZ** [comment]
> you mean I run exe in command line and append these setting like --proxy-server=... ?

try `"Polar Bookshelf.exe" --proxy-server=socks5://127.0.0.1:1080`. It works on my computer
