### ISSUE TITLE
Snap install - weird error when clossing the app

### ISSUE THREAD

**Issue by cdorin93** [burtonator/polar-bookshelf#391]
NOTE: Polar is supported by community donations.  Bug reports and features are prioritized for people who make a donation: https://opencollective.com/polar-bookshelf

**Describe the bug**

**To Reproduce**
1. Install the snap
2. Press X to close the app
3. 
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #<WebContents>
    at detachGuest (/snap/polar-bookshelf/18/resources/electron.asar/browser/guest-view-manager.js:283:18)
    at WebContents.guest.once (/snap/polar-bookshelf/18/resources/electron.asar/browser/guest-view-manager.js:88:7)
    at Object.onceWrapper (events.js:273:13)
    at WebContents.emit (events.js:187:15)
    at WebContents.EventEmitter.emit (domain.js:442:20)
    at WebContents.topLevelDomainCallback (domain.js:121:23)
```

**Expected behavior**
App to close properly

**Desktop (please complete the following information):**
 - OS: Solus OS
 - Version [1.0.11] (snap)

Thanks for the app! there is a lot of potential in it. Keep up the good pace :)

**Comment by cdorin93** [comment]
Ok, so the error seems to appear only when you close the app after uploading a pdf. Closing it and reopening the app solves the issue.
