### ISSUE TITLE
"Uncaught exception:  TypeError: Error processing argument at index 0, conversion failure from #<WebContents>"

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#578]
Getting this error still in Electron. 

I think the guestInstances map is becoming polluted with the wrong type.

```
[error] [1.9.0] [MainAppExceptionHandlers.js] Uncaught exception:  TypeError: Error processing argument at index 0, conversion failure from #<WebContents>
    at detachGuest (/home/burton/projects/polar-bookshelf/node_modules/electron/dist/resources/electron.asar/browser/guest-view-manager.js:283:18)
    at WebContents.guest.once (/home/burton/projects/polar-bookshelf/node_modules/electron/dist/resources/electron.asar/browser/guest-view-manager.js:88:7)
    at Object.onceWrapper (events.js:273:13)
    at WebContents.emit (events.js:187:15)
    at WebContents.EventEmitter.emit (domain.js:442:20)
    at WebContents.emitter.emit.args [as emit] (/home/burton/projects/polar-bookshelf/node_modules/@sentry/electron/src/main/integrations/electron.ts:65:14)
    at WebContents.topLevelDomainCallback (domain.js:121:23)

```

see if I can monkey patch this in the mean time at the very minimum to test if I have a fix that will work.

**Comment by leniNikky** [comment]
i got the same error, have u solved this problem
