### ISSUE TITLE
not running on ubuntu

### ISSUE THREAD

**Issue by cpaysantler** [burtonator/polar-bookshelf#635]
NOTE: Polar is supported by community donations.  Bug reports and features are prioritized for people who make a donation: https://opencollective.com/polar-bookshelf

**Describe the bug**
polar-bookshelf is not running on my computer

**Screenshots**
cpaysan-loc@A140090:~$ polar-bookshelf 
polar-bookshelf: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by polar-bookshelf)
/opt/Polar Bookshelf/polar-bookshelf: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /opt/Polar Bookshelf/polar-bookshelf)
[ManualUpdates.js] Allowing pre-releases for auto-updates: false
Quiting.  App is single instance.
Running with app path: /opt/Polar Bookshelf/resources/app.asar
Running with CWD: /home/cpaysan-loc
Running with node version: v10.2.0
body-parser deprecated undefined extended: provide extended option ../../opt/Polar Bookshelf/resources/app.asar/web/js/backend/webserver/Webserver.js:50:44
Unable to launch app:  { Error: Cannot find module 'qs'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/opt/Polar Bookshelf/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at parser (/opt/Polar Bookshelf/resources/app.asar/node_modules/body-parser/lib/types/urlencoded.js:225:13)
    at extendedparser (/opt/Polar Bookshelf/resources/app.asar/node_modules/body-parser/lib/types/urlencoded.js:136:15)
    at Function.urlencoded (/opt/Polar Bookshelf/resources/app.asar/node_modules/body-parser/lib/types/urlencoded.js:65:7)
    at Webserver.<anonymous> (/opt/Polar Bookshelf/resources/app.asar/web/js/backend/webserver/Webserver.js:50:44)
    at Generator.next (<anonymous>) code: 'MODULE_NOT_FOUND' }

**Desktop (please complete the following information):**
 Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
 - Browser firefox

**Comment by burtonator** [comment]
Definitely not tested on 14.04... Try the AppImage or snap ?
