### ISSUE TITLE
Invalid package app.asar

### ISSUE THREAD

**Issue by ngirard** [burtonator/polar-bookshelf#788]
Using polar-bookshelf-1.15.2-amd64.deb on Ubuntu 18.10, this error message is logged multiple times:

`Error: Invalid package /opt/Polar Bookshelf/resources/app.asar/opt/Polar Bookshelf/resources/app.asar
    at invalidArchiveError (ELECTRON_ASAR.js:147:19)
    at Object.fs.lstat (ELECTRON_ASAR.js:280:16)
    at ELECTRON_ASAR.js:311:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
`

**Comment by burtonator** [comment]
Is it just a logged error or is anything breaking?

**Comment by ngirard** [comment]
Well, Polar seems to work despite the error message, but I couldn't guarantee that everything works. (Sorry for the late reply)
