### ISSUE TITLE
Using pagemarks causes "EPERM: operation not permitted, rename"

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#894]
Creating new pagemarks, either via "Create Pagemark to Point" or CTRL+Alt+N, causes an error like this in the console:

```
Uncaught (in promise) EPERM: operation not permitted, rename 'C:\Users\Tracy\.polar\18d3258cc20a8fd79a5f32b91eb6e582\.state.json-410162' -> 'C:\Users\Tracy\.polar\18d3258cc20a8fd79a5f32b91eb6e582\state.json'
```

The new pagemark does save successfully, though.

I did not experience this behavior on the previous version (1.17.5, I think). It is possibly relevant that my `.polar` directory is a junction to another drive.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 1.18.1

**Comment by burtonator** [comment]
It's probably not written to disk unfortunately.  

Does this work for ALL files or just previous ones?

I enabled a new feature for this but it appears to break sometimes on Windows.

**Comment by sopoforic** [comment]
Upon further testing, it seems to happen with one document in particular; I tried several others and got no error, but the document mentioned above does it every time. The document in question is one added after updating polar, but other documents added after updating work correctly.

The changes did get persisted to disk; I had fully exited polar and re-opened it to check before submitting this issue.

**Comment by burtonator** [comment]
Thanks.. Do you just get the error in the console or one inside Polar as well.  

Now that I think about it, what might be happening here is that Windows is actually CATCHING a duplicate content write error due to these being idempotent writes. It might be refusing to overwrite if a rename action is currently being performed.  

Just thinking out loud and not sure why it's only impacting one document.

I saw it on my end but when I copied the state.json to a tmp file and back it never did it again.  I assumed it was a errant bug that I couldn't duplicate (which happens some time).

I'm going to need to think of a work around here as I can't always duplicate it on my end.

**Comment by sopoforic** [comment]
Polar gives me the red "internal error" bubble and has that error in the console, but otherwise everything apparently works fine.

**Comment by sopoforic** [comment]
These are still happening:

```
Uncaught (in promise) EPERM: operation not permitted, rename 'C:\Users\Tracy\.polar\0969c557b1584b45aba3688aee1d9071\.state.json-164506' -> 'C:\Users\Tracy\.polar\0969c557b1584b45aba3688aee1d9071\state.json'
    at Function.<anonymous> (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\polar-shared\src\util\Files.ts:577:24)
    at Generator.next (<anonymous>)
    at C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\polar-shared\src\util\Files.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\polar-shared\src\util\Files.js:4:12)
    at Function.withProperException (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\polar-shared\src\util\Files.js:387:16)
    at Function.<anonymous> (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\polar-shared\src\util\Files.ts:497:21)
    at Generator.next (<anonymous>)
    at C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\polar-shared\src\util\Files.js:8:71
    at new Promise (<anonymous>)
```

**Comment by burtonator** [comment]
You're on a recent version of Polar?

**Comment by sopoforic** [comment]
Yes, I'm still getting it on 1.40.1.
