### ISSUE TITLE
Create pagemark fails with progress > 100

### ISSUE THREAD

**Issue by sopoforic** [burtonator/polar-bookshelf#913]
When creating a pagemark with "Create Pagemark to Point" in a PDF, it occasionally fails with an error like this:

```
C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\@sentry\browser\dist\index.js:3680 [error] [1.18.1] [PagemarkCoverageEventListener.js] Failed to create pagemark:  Error: Assertion failed for value 100.00000000000001: Progress value invalid. Must be within interval [0-100]
    at Function.assert (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\Preconditions.js:9:19)
    at Function.create (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\ReadingProgresses.js:8:39)
    at writeReadingProgress (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\Pagemarks.js:276:75)
    at Function.doPageMetaMutation (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\Pagemarks.js:284:9)
    at C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\Pagemarks.js:175:18
    at C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\Pagemarks.js:252:13
    at Function.withBatchedMutations (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\DocMetas.js:108:13)
    at Function.doDocMetaMutation (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\Pagemarks.js:251:29)
    at Function.updatePagemark (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\Pagemarks.js:173:14)
    at C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\Pagemarks.js:86:31
    at Function.withBatchedMutations (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\DocMetas.js:108:13)
    at Function.updatePagemarksForRange (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\metadata\Pagemarks.js:80:29)
    at Model.<anonymous> (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\model\Model.js:110:56)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\web\js\model\Model.js:4:58)
(anonymous) @ C:\Users\Tracy\AppData\Local\Programs\polar-bookshelf\resources\app.asar\node_modules\@sentry\browser\dist\index.js:3680
```

Retrying the operation succeeds (perhaps due to different pointer position?).

This is not the same bug as #620.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version 1.18.1

**Comment by burtonator** [comment]
Thanks.. fun with floating points!  I put some more checks in there to force them to integers which hopefully fixes the problem
