### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by Rumata888** [burtonator/polar-bookshelf#977]
Got this error popup.
ConsoleLogger.ts:23 [error] [1.19.4] [PersistenceLayers.js] Unable to sync between source and target:  Object FirebaseError: The value of property "value" is longer than 1048487 bytes.
    at new t (http://localhost:8500/node_modules/firebase/firebase.js:1:422428)
    at http://localhost:8500/node_modules/firebase/firebase.js:1:516897
    at uh.<anonymous> (http://localhost:8500/node_modules/firebase/firebase.js:1:516134)
    at uh.Cs.ua (http://localhost:8500/node_modules/firebase/firebase.js:1:385893)
    at uh.Cs.dispatchEvent (http://localhost:8500/node_modules/firebase/firebase.js:1:385302)
    at lh.ob (http://localhost:8500/node_modules/firebase/firebase.js:1:419468)
    at oh.Cs.Ad (http://localhost:8500/node_modules/firebase/firebase.js:1:416949)
    at oh.Cs.bc (http://localhost:8500/node_modules/firebase/firebase.js:1:415168)
    at Sc.Cs.Wa (http://localhost:8500/node_modules/firebase/firebase.js:1:394107)
    at Sc.Cs.vb (http://localhost:8500/node_modules/firebase/firebase.js:1:392683)

**Comment by burtonator** [comment]
@Rumata888 This is fascinating.. that's a HUGE amount of metadata/annotations in one .json file.  

Could you email it to me so I can take a look?  Do you have a lot of annotations there? 

You could just attach it here via https://send.firefox.com/

or we could arrange private email. 

it should be a > 1MB state.json file under your .polar dir.  If you're on a Linux/Mac machine I could give you a command to easily find it.  Might work on Windows too.

**Comment by Rumata888** [comment]
https://send.firefox.com/download/d54c6b98ed03fb38/#7e33r8IbYOZYya5qqhJVRQ

**Comment by burtonator** [comment]
Thanks.. ok. I have a short term fix for this that will work for the forseeable future.  

I'll push it out early next week. For now I think it's safe to just ignore these sync issues and the file will start working once the new version is upgraded.

I think you will have to make a change to the file though so it makes a smaller version.

BTW. How is this large PDF working (except for this issue.)

1500 pages is pretty large and we used to not work very well with large PDFs (glad that's mostly behind us)

**Comment by burtonator** [comment]
If I drop whitespace and implement SPARSE support where the pageMeta is added/removed on serialize/deserialize I can get about a 10x reduction in space used.

10x is MORE than enough to handle this. This would mean books with about 10k pages.

**Comment by Rumata888** [comment]
Great. BTW, how should I backup before the next update? Just copy .polar?

**Comment by burtonator** [comment]
Yeah.Doesn't hurt. We will cut a release early next week.

**Comment by Rumata888** [comment]
Has the patch been applied in 1.19.4? Or will it come with a later release?

**Comment by burtonator** [comment]
1.19.7 has this fix so if you could verify that it resolves your issue that would be great.

**Comment by Rumata888** [comment]
Seems to work. However, there is a new error:
RendererAnalytics.ts:314 Operation took too long: datastore:write: 2585ms

**Comment by burtonator** [comment]
That's just a warning. I might not enable those in production so not to confuse people.  I'm not upset that some of these operations take long but in this case it WAS sending about 500k.

**Comment by leogodin217** [comment]
I just got the same error. I do make a lot of annotations and Anki flashcards. One thing I do is to paste screenshots into the flashcard and I suspect that is what is causing the issue.

**Comment by burtonator** [comment]
@leogodin217 YES.  That's the issue.  Back in the day I implemented a change to data URL encode the screenshot / image.

The problem is that this means that the URL is encoded directly into the JSON.

I'm going to work on a change to catch that use case and convert these to image URLs and NOT actually encoded data URLs inside the JSON.  It's going to take a while though so maybe try to keep this to a minimum or use area highlights which are a new feature but they take screenshots and properly use 'files' in Polar which are not stored in the JSON directly.

**Comment by leogodin217** [comment]
@burtonator Thanks. I do use area highlights, but I want the images in my flash cards. I don't think we have a way to include the area highlight. Either way, I'm fine waiting to sync everything. I'll just backup my .polar directory.

**Comment by burtonator** [comment]
@leogodin217 yes.. I would like that too. I agree.

**Comment by leogodin217** [comment]
@burtonator How difficult a story is storing the images instead of embedding them? I'd be happy to work on it. I'm a pretty good programmer, but I've been working with Python and R for the last several years. Very little JavaScript. I'd be happy to pick up TypeScript and take a stab at it.

**Comment by burtonator** [comment]
It's not too hard I think.. I just don't have the time to tackle it as I"m working on landing 2-3 huge branches.

the summernote plugin has a paste handler which takes the clipboard data and converts it to a data: URL.

It would need to be updated to compute binary png of the data then call writeFile on the datastore to add a binary fiile to your datastore/persistence layer backend.

This API is the same for firebase/disk/etc.

Then you just call getFile() and it will return a URL for the image.

One problem is that the URL changes every time you run polar in a different configuration.  So for disk it could be a file URL and for the web it will be an https URL.

We probably need some sort of custom URL to store in the HTML which is rewritten before it's presented to the user in the DOM.

Another challenge is that we have to push teh persistence layer up through the react components to get to the summernote extension.  

This shouldn't be too hard. It's probably 1-3 hours worth of work.  Not insane really.

**Comment by leogodin217** [comment]
I spent a few hours looking at this, but I don't know enough JavaScript and React to do anything. Sorry. For now, I will delete image flashcards after syncing with Anki. That should be a good enough workaround. Learning React is on my to-do list, but not for a few months.

**Comment by FilipBB** [comment]
I recently encountered this problem: my state.json is 1040204 bytes and it won't sync back to the server. Is there a workaround or a way to increase the limit?

**Comment by thiswillbeyourgithub** [comment]
I don't see any reason for a limit that low : Polar is incedibly useful for large documents (in my case it's a professional pdf of hundreds of pages with volumes of diagrams) and the 1Mb mark is hit fairly easily.

Moreover : I spent way too much time trying to figure out what was the issue, there is no clear mention of the size limit in the error I get, even when looking through the logs. Thankfully I found mentions of this in the issues in this repo

**Comment by Deagler** [comment]
Still getting this issue A LOT - on a small 15 page pdf but it overflowed past 1MB because of screenshots I had in flashcards.

**Comment by thiswillbeyourgithub** [comment]
Still awaiting for this fix :/
